name: Build and test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v2
      
      - name: Set current week of the year in environnement
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        run: echo "::set-env name=CURRENT_WEEK::$(date +%V)"
      
      - name: Set current week of the year in environnement
        if: startsWith(matrix.os, 'windows')
        run: echo "::set-env name=CURRENT_WEEK::$(Get-Date -UFormat %V)"

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.rust }}-${{ matrix.os }}-cargo-registry-${{ env.CURRENT_WEEK }}-build_and_test
      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ matrix.rust }}-${{ matrix.os }}-cargo-index-${{ env.CURRENT_WEEK }}-build_and_test
      - name: Cache cargo binaries
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ matrix.rust }}-${{ matrix.os }}-cargo-binaries-${{ env.CURRENT_WEEK }}-build_and_test
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.rust }}-${{ matrix.os }}-cargo-build-target-${{ env.CURRENT_WEEK }}-build_and_test

      - name: Install latest ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.rust }}
            profile: minimal
            override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --benches --bins --examples --tests --all-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  cross:
    name: Cross compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - i686-unknown-linux-gnu
          - powerpc-unknown-linux-gnu
          - powerpc64-unknown-linux-gnu
          - powerpc64le-unknown-linux-gnu
          - mips-unknown-linux-gnu
          - arm-linux-androideabi

    steps:
    - uses: actions/checkout@v2
    
    - name: Set current week of the year in environnement
      run: echo "::set-env name=CURRENT_WEEK::$(date +%V)"
    
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ env.CURRENT_WEEK }}-cross
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ env.CURRENT_WEEK }}-cross
    - name: Cache cargo binaries
      uses: actions/cache@v1
      with:
        path: ~/.cargo/bin
        key: cargo-binaries-${{ env.CURRENT_WEEK }}-cross
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: target
        key: ${{ matrix.target }}-cargo-build-target-${{ env.CURRENT_WEEK }}-cross

    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Install cross
      run: cargo install cross || true

    - name: check
      run: cross check --target ${{ matrix.target }}

    - name: test
      run: cross test --target ${{ matrix.target }}
